apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: complex
build:
  artifacts:
  - image: postgres
    context: client
    docker:
      dockerfile: Dockerfile.dev
  - image: raunakjodhawat/multi-client
    context: server
    docker:
      dockerfile: Dockerfile.dev
  - image: raunakjodhawat/multi-server
    context: worker
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s/client-cluster-ip-service.yaml
    - k8s/client-deployment.yaml
    - k8s/database-persistent-volume-claim.yml
    - k8s/ingress-service.yml
    - k8s/postgres-cluster-ip-service.yaml
    - k8s/postgres-deployment.yaml
    - k8s/redis-cluster-ip-service.yaml
    - k8s/redis-deployment.yaml
    - k8s/server-cluster-ip-service.yaml
    - k8s/server-deployment.yaml
    - k8s/worker-deployment.yaml
